string in
---
std_msgs/Header header
std_msgs/Bool done
std_msgs/Bool crash
sensor_msgs/Image image
sensor_msgs/Image prob_image
geometry_msgs/Point current_position
geometry_msgs/Point goal_position
