#rl state
heading_dim: 1
velocity_dim: 1
action_dims: 2
state_dims: 2
n_channels: 4
img_height: 128
img_width: 128

high_vel: 3
low_vel: 0

high_heading: 3
low_heading: 0

value_lr: 0.0001
q_lr: 0.0001
policy_lr: 0.0001

batch_size: 64
latent_dims: 64
replay_size: 5000

gamma: 0.95
soft_tau: 0.01

max_episodes: 500
max_episode_len: 1000

GPU: True
mapping: False

simulation_max_x: 1000
simulation_min_x: 0
simulation_max_y: 1000
simulation_min_y: 0

completion_reward: 100
crash_reward: -100
dist_reward_weight: 0.05

root_dir: '/home/ravi/Ravi_D/Acadamic/UPENN/Third_sem/CIS_700_02/Project/Reinforcement-Learning-for-Drone-Control' 

logging_path: '/logging/training_curves/'
value_network_path: '/logging/value_net.pth'
value_network_path: '/logging/policy_net.pth'
softq1_path: '/logging/softq1_net.pth'
softq2_path: '/logging/softq2_net.pth'
reward_array_path: '/logging/rewards.npy'

observation_path: '/buffer/obs/'
next_observation_path: '/buffer/next_obs/'
